blank_issues_enabled: true

contact_links:
  - name: 💬 Join Our Whatsapp Group 💬
    url: https://chat.whatsapp.com/FGV7ef4d9tNGtfN8HDvbim
    about: Feel free to ask questions or help others in our friendly community! 🚀

  - name: 📢 Subscribe to Update Channel 📢
    url: https://chat.whatsapp.com/FVeZfhzV68iEPAwRTpMdLh
    about: Stay updated with the latest news, releases, and exciting updates in the world of Demon! 🌟
